TrainForTheRoleAspNetCore.Mvc/ViewModels/Tickets/CreateViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace TrainForTheRoleAspNetCore.Mvc.ViewModels.Tickets
{
    public class CreateViewModel
    {
        [Required, MaxLength(50)]
        public string Title { get; set; }

        [Required, MaxLength(1000)]
        public string Description { get; set; }

        [Required]
        public int? Status { get; set; }
    }
}

TrainForTheRoleAspNetCore.Mvc/ViewModels/Tickets/DetailsViewModel.cs
using System;
namespace TrainForTheRoleAspNetCore.Mvc.ViewModels.Tickets
{
    public class DetailsViewModel
    {
        public DetailsViewModel()
        {
        }
    }
}

TrainForTheRoleAspNetCore.Mvc/ViewModels/Tickets/IndexViewModel.cs
using System;
using Api;

namespace TrainForTheRoleAspNetCore.Mvc.ViewModels.Tickets
{
    public class IndexViewModel
    {
        public IndexViewModel()
        {
        }

        public TicketPagedResult Paged { get; set; }
    }
}

TrainForTheRoleAspNetCore.Mvc/ViewModels/Tickets/UpdateViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace TrainForTheRoleAspNetCore.Mvc.ViewModels.Tickets
{
    public class UpdateViewModel
    {
        [Required]
        public Guid? Id { get; set; }

        [Required, MaxLength(50)]
        public string Title { get; set; }

        [Required, MaxLength(1000)]
        public string Description { get; set; }

        [Required]
        public int? Status { get; set; }
    }
}

TrainForTheRoleAspNetCore.Mvc/Controllers/TicketsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using TrainForTheRoleAspNetCore.Domain;
using TrainForTheRoleAspNetCore.Domain.Models;
using TrainForTheRoleAspNetCore.Mvc.ViewModels.Tickets;

namespace TrainForTheRoleAspNetCore.Mvc.Controllers
{
    [Authorize]
    public class TicketsController : BaseController
    {
        public TicketsController(ILogger<BaseController> logger, ServiceWrapper serviceWrapper, IConfiguration configuration) : base(logger, serviceWrapper, configuration)
        {
        }

        public async Task<IActionResult> Index(string q, int? p = 1)
        {
            return View(new IndexViewModel()
            {
                Paged = await this.ApiClient.SearchTicketsAsync(p, q)
            });
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateViewModel model)
        { 
            if (!ModelState.IsValid)
                return View(model);

            var status = (Api.TicketStatus)model.Status;

            await this.ApiClient.PostTicketAsync(new Api.Ticket()
            {
                Title = model.Title,
                Description = model.Description,
                Status = status,
                UserId = this.UserId
            });

            return RedirectToActionPermanent("Index");
        }

        public async Task<IActionResult> Update(Guid id)
        {
            var ticket = await this.ApiClient.GetTicketAsync(id);

            return View(new UpdateViewModel()
            {
                Id = ticket.Id,
                Title = ticket.Title,
                Description = ticket.Description,
                Status = (int)ticket.Status
            });
        }

        [HttpPost]
        public async Task<IActionResult> Update(Guid id, UpdateViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var status = (Api.TicketStatus)model.Status;

            await this.ApiClient.UpdateTicketAsync(new Api.Ticket()
            {
                Title = model.Title,
                Description = model.Description,
                Status = status,
                UserId = this.UserId
            });

            return RedirectToActionPermanent("Index");
        }

        public async Task<IActionResult> Delete(Guid? id)
        {
            if (!ModelState.IsValid)
                return RedirectToActionPermanent("Index");

            await this.ApiClient.DeleteTicketAsync(id.Value);

            return RedirectToActionPermanent("Index");
        }
    }
}

TrainForTheRoleAspNetCore.Mvc/Views/Tickets/Create.cshtml
@model TrainForTheRoleAspNetCore.Mvc.ViewModels.Tickets.CreateViewModel

@{
    ViewData["Title"] = "New Ticket";
}

<form asp-controller="Tickets" asp-action="Create" method="post">
    <div class="form-group">
        <label for="exampleInputEmail1">Title</label>
        <input asp-for="Title" class="form-control" placeholder="Title here">
        <span asp-validation-for="Title"></span>
    </div>

    <div class="form-group">
        <label for="exampleFormControlTextarea1">Description</label>
        <textarea asp-for="Description" class="form-control" rows="3"></textarea>
        <span asp-validation-for="Description"></span>
    </div>

    <div class="form-group">
        <select asp-for="Status" class="custom-select custom-select-lg mb-3">
            <option value="">Select Status</option>
            <option value="0">Pending</option>
            <option value="1">In Progress</option>
            <option value="2">Closed</option>
        </select>
        <span asp-validation-for="Status"></span>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>

TrainForTheRoleAspNetCore.Mvc/Views/Tickets/Index.cshtml
@model TrainForTheRoleAspNetCore.Mvc.ViewModels.Tickets.IndexViewModel

@{
    ViewData["Title"] = "Tickets";
}

<h1>Tickets</h1>

<form asp-controller="Tickets" asp-action="Index" method="get">
    <div class="input-group mb-3">
        <input name="q" value="@Model.Paged.Keyword" type="text" class="form-control" placeholder="Recipient's username" aria-label="Recipient's username" aria-describedby="basic-addon2">
        <div class="input-group-append">
            <button class="btn btn-outline-secondary" type="submit">Search</button>
            <a asp-action="Create" class="btn btn-outline-secondary">New</a>
        </div>
    </div>
</form>

@if (Model.Paged.RowCount > 0)
{
    <table class="table table-hover table-sm">
        <thead>
            <tr>
                <th>Title</th>
                <th>Status</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var ticket in Model.Paged.Results)
            {
                var status = "Pending";
                @switch (ticket.Status)
                {
                    case Api.TicketStatus._0:
                        status = "Pending";
                        break;
                    case Api.TicketStatus._1:
                        status = "In Progress";
                        break;
                    case Api.TicketStatus._2:
                        status = "closed";
                        break;
                }

                <tr>
                    <td>@ticket.Title</td>
                    <td>@status</td>
                    <td>
                        <a asp-controller="Tickets" asp-action="Update" asp-route-id="@ticket.Id">Update</a>
                        <a asp-controller="Tickets" asp-action="Delete" asp-route-id="@ticket.Id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

    @if (Model.Paged.PageCount > 1)
    {
        <nav aria-label="Page navigation example">
            <ul class="pagination">
                @if (Model.Paged.CurrentPage != 0)
                        {
                    <li class="page-item"><a class="page-link" href="#">Previous</a></li>
                }

                    @for (int i = 1; i > Model.Paged.PageCount; i++)
                {
                    <li class="page-item"><a class="page-link" href="#">@i</a></li>
                }

                @if (Model.Paged.CurrentPage >= Model.Paged.PageCount)
                {
                    <li class="page-item"><a class="page-link" href="#">Next</a></li>
                }
            </ul>
        </nav>
    }
}

TrainForTheRoleAspNetCore.Mvc/Views/Tickets/Update.cshtml
@model TrainForTheRoleAspNetCore.Mvc.ViewModels.Tickets.UpdateViewModel

@{
    ViewData["Title"] = "Update Ticket";
}

<form asp-controller="Tickets" asp-action="Create" asp-route-id="@Model.Id" method="post">
    <div class="form-group">
        <label for="exampleInputEmail1">Title</label>
        <input asp-for="Title" class="form-control" placeholder="Title here">
        <span asp-validation-for="Title"></span>
    </div>

    <div class="form-group">
        <label for="exampleFormControlTextarea1">Description</label>
        <textarea asp-for="Description" class="form-control" rows="3"></textarea>
        <span asp-validation-for="Description"></span>
    </div>

    <div class="form-group">
        <select asp-for="Status" class="custom-select custom-select-lg mb-3">
            <option value="">Select Status</option>
            <option value="0">Pending</option>
            <option value="1">In Progress</option>
            <option value="2">Closed</option>
        </select>
        <span asp-validation-for="Status"></span>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>